services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_pg
      MYSQL_USER: adi
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-network

  spring-app:
    build: .
    container_name: spring-app
    environment:
      DB_HOST: mysql-db
      DB_NAME: my_pg
      DB_PORT: 3307
      DATASOURCE_USERNAME: adi
      DATASOURCE_PASSWORD: root
    ports:
      - "5555:8080"
    depends_on:
      - mysql
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql-data:
