services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_pg
      MYSQL_USER: adi
      MYSQL_PASSWORD: PG2024
    networks:
      - mynetwork
    volumes:
      - pg_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5555:5555"  # Assuming your Spring Boot app runs on port 8080
    environment:
      DB_PORT: 3307
      DB_NAME: my_pg
      DB_USERNAME: adi
      DB_PASSWORD: PG2024
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pg_data: